# numpy

In [6]:
import matplotlib # 시각화
import numpy as np # 별칭
print(np.__version__) # 상위 오브젝트가 가진 속성
def pprint(arr): # ndarray : numpy의 기본 데이터 배영
    print('type : {}'.format(type(arr)))
    print('shape : {}, dimension : {}, dtype : {}'.format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data : \n",arr)
          
arr = [1, 2, 3] # 리스트
a = np.array([1, 2, 3]) # ndarray
b = np.array(arr)
pprint(a)
print()
pprint(b)

1.16.5
type : <class 'numpy.ndarray'>
shape : (3,), dimension : 1, dtype : int32
Array's Data : 
 [1 2 3]

type : <class 'numpy.ndarray'>
shape : (3,), dimension : 1, dtype : int32
Array's Data : 
 [1 2 3]


In [10]:
# 인스턴스상태
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) # ndarray
print(id(a)) # python core 주소값 확인
print(a.size) # 데이터 개수 
print(a.astype(np.float32)) # 대이터 타입 변경, numpy는 행중심, 동질적
print(a.dtype.itemsize*a.size) # 전체 메모기 사이즈 (바이트)
# iterator for in range => lsit
a = np.arange(1000) # arange => ndarray
a

2662624098784
10
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
40


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [15]:
# ndarray 초기화 함수들
print(np.zeros((3, 4)))
print()
print(np.ones((2, 3, 4), dtype=np.int16))  # 1, 3차원 면, 행, 열
print()
print(np.full((2, 2), 7))
print()
print(np.eye(4)) # 댇각형렬 identity, 행렬연산에거 항등원 +, *
print()
print(np.empty((4, 2))) # 쓰래기값

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]

[[7 7]
 [7 7]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 5.47424736e-321]
 [1.24611741e-306 1.11261027e-306]]


In [18]:
a = np.arange(0, 100, 10) # ndarray
indices = [1, 5, -1] # list
print(indices)
b = a[indices] # 리스트를 첨자로 사용, a[1], a[5], a[-1]
print(a)
print(b)

[1, 5, -1]
[ 0 10 20 30 40 50 60 70 80 90]
[10 50 90]


In [27]:
a = np.arange(11, 36) # 1차원
print(a)
a.shape = (5, 5) # 개수가 맞아야함
print(a)
print(type(a))
print(a.dtype)
print(a.size)
print(a.shape) # 차수
print(a.ndim) # 2차원
print(a.nbytes) # 100바이트 = 25*4
print(a.strides) # (20,4) 다음열의 데이터는 몇바이트를 건너 뛰어야 하는가, 다음행은 몇바이트를 건너뛰어야 하는가

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35]
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
<class 'numpy.ndarray'>
int32
25
(5, 5)
2
100
(20, 4)


In [28]:
arr = np.arange(10)
print(type(arr))
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8] = 12
print(arr[1:6])

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 1  2  3  4 12]


In [32]:
# numpy 첨자생략 불가
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[0]) # 행우선 : 행
print(arr2d[0][2])
print(arr2d[0,2])
print(arr2d[:2]) # 0,1 행
print(arr2d[:2,1:])
print(arr2d[1,:2])
arr2d[:2,:1] = 0
arr2d[:2,:1] = 0
print(arr2d)

# array, ndarray
print(type(arr2d))


[1 2 3]
3
3
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
[4 5]
[[0 2 3]
 [0 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [33]:
# 실제 저장은 일렬로 사람이 데이터를 다루는 것은 입체로 전체 480바이트
# 해렬연산에서 앞의 행렬열수와 뒤의 행렬의 행수를 일치 시켜야 행렬곱이 가능
# 행렬곱에서 행렬 앞뒤로 바꾸면 안됨
print("스트라이드 값 : ", np.ones((3,4,5), dtype=np.float64).strides)
# 단일 데이터 float64 : 8바이트

스트라이드 값 :  (160, 40, 8)


In [51]:
# 문제
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # 2,2,3
print("첫면", arr3d[0])
print('첫차원 첫행', arr3d[0,0])
print('첫요소',arr3d[0,0,0])
print(arr3d[1,0,1])
print(arr3d[1,1,2]) # 면, 행, 열([면][행][열])

첫면 [[1 2 3]
 [4 5 6]]
첫차원 첫행 [1 2 3]
첫요소 1
8
12


In [52]:
# 백업이 안됨 : 대임하면 같은 주소를 가리키기 때문에 
old_values=arr3d.copy() # 대입 : 주소를 복사
arr3d[0]=42
print('값의 변경후')
print(arr3d)
print('이전값으로 ')
arr3d = old_values
print(arr3d)

값의 변경후
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
이전값으로 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [56]:
Z = np.arange(36)
print(Z)
print()
Z = Z.reshape((6,6))
print(Z)
print()
reshape2 = Z.reshape((2,3,6))
print(reshape2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]


In [64]:
arr=np.arange(32).reshape((8,4))
print(arr)
print()
print(arr[[1,5,7,2]]) # 행중심
print()
print(arr[[-1,-5,-7,-2]]) # 거꾸로 인덱싱
print()
print(arr[[1,5,7,2],[0,3,1,2]]) # [1][0], [7][3],...
print()

print(arr[[1,2,5,7]][:])
print()
print(arr[[1,5,7,2]][:,[0,3,1,2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]

[[28 29 30 31]
 [12 13 14 15]
 [ 4  5  6  7]
 [24 25 26 27]]

[ 4 23 29 10]

[[ 4  5  6  7]
 [ 8  9 10 11]
 [20 21 22 23]
 [28 29 30 31]]

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [73]:
arr = []
for i in range(6):
    ad=[]
    for j in range(6):
        ad.append(i*10 +j)
    arr.append(ad)
print(arr)
arr = np.array(arr)

[[0, 1, 2, 3, 4, 5], [10, 11, 12, 13, 14, 15], [20, 21, 22, 23, 24, 25], [30, 31, 32, 33, 34, 35], [40, 41, 42, 43, 44, 45], [50, 51, 52, 53, 54, 55]]


In [81]:
orange = arr[[0,1,2,3,4],[1,2,3,4,5]]
print(orange)

[ 1 12 23 34 45]


In [82]:
red = arr[[0,2,5],[2,2,2]]
# arr[[0,2,5],2]
print(red)

[ 2 22 52]


In [83]:
skyblue = arr[[3,4,5]][:,[0,2,5]]
# arr[3:6][:,0,2,5]
print(skyblue)

[[30 32 35]
 [40 42 45]
 [50 52 55]]


In [85]:
red = arr[:,[2]]

array([[ 2],
       [12],
       [22],
       [32],
       [42],
       [52]])

In [103]:
orange = arr[[0]][:,[3,4]]
# arr[0,[3,4]]

array([[3, 4]])

In [104]:
green = arr[[2,4]][:,[0,2,5]]


array([[20, 22, 25],
       [40, 42, 45]])

In [105]:
blue = arr[[4,5]][:,[4,5]]

array([[44, 45],
       [54, 55]])

In [114]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) # 4x3
v = np.array([1,0,1])
print('타일출력')
vv = np.tile(v,(4,1))
# [[1 0 1]
#  [1 0 1]
#  [1 0 1]
#  [1 0 1]]
print(vv)
y = x+vv # 4x3 배열연산 => 요소별 연산
print(y)
# 배열연산 : 양쪽 차원이 일치해야함
print(x+v)
print(x +3) # 4x3, 1x3 broadcasting

타일출력
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [116]:
a = np.arange(1,13)
a.shape = (4,3)
print(a)
print(a.ndim)
print(a.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)


In [117]:
x = np.arange(6).reshape((3,2))
print(x)

[[0 1]
 [2 3]
 [4 5]]


In [119]:
# 거듭제곱(행열곱)
# x@x => 앞의 행렬 열수와 뒤의 행렬의 행수가 일치해야함
# 전치행렬 열과 행을 뒤집는것
x@x.T
# np.transpose(x)

array([[0, 2, 4],
       [1, 3, 5]])

In [122]:
arr = np.arange(24).reshape((2,3,4))
print(arr)
print(arr.transpose((1,0,2))) # 면,행,열 순서 변경 3,2,4
print(arr.transpose((0,2,1))) # 2,4,3

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
[[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]


In [127]:
# Boolean indexing (True/False)
# 문자열은 대소문자 구분
names= np.array(['Seoul','Daejun','Chungju','seoul','chungju','Daejun','Daejun'])
data = np.random.randn(7,4)
print(names =='Seoul') # 1,0,0,0,0,0,0
print(data[names=='Seoul']) # 7x4에서 True는 0번째 0번째 랜덤값 list print
print(data[names=='Seoul',2:])
print(data[names=='Seoul',3])
print(names != 'Seoul')
print(~(names=='Seoul'))
mask = (names=='Seoul')|(names=='shungju')
print(mask)
print(data[mask])

[ True False False False False False False]
[[ 0.48716523 -0.11894411 -0.18704164 -0.43842514]]
[[-0.18704164 -0.43842514]]
[-0.43842514]
[False  True  True  True  True  True  True]
[False  True  True  True  True  True  True]
[ True False False False False False False]
[[ 0.48716523 -0.11894411 -0.18704164 -0.43842514]]


In [130]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True, False, True, True, False])
print(zip(xarr,yarr, cond)) # zip 요소별로 데이터를 묶는다.
print(list(zip(xarr, yarr, cond)))
result = [(x if c else y) for x,y,c in zip(xarr, yarr, cond)] # 3 항연산자
print('result : ',result)    

[(1.1, 2.1, True), (1.2, 2.2, False), (1.3, 2.3, True), (1.4, 2.4, True), (1.5, 2.5, False)]
result :  [1.1, 2.2, 1.3, 1.4, 2.5]


In [131]:
result = np.where(cond, xarr, yarr)
print(result)

[1.1 2.2 1.3 1.4 2.5]


In [134]:
for x,y,c in zip(xarr,yarr,cond):
    if c:
        print(x)
    else:
        print(y)

1.1
2.2
1.3
1.4
2.5


In [132]:
# random 난수 정규분포에 출력 16개 출력
arr = np.random.randn(4,4)
print(arr)
print(np.where(arr>0,2,-2))

[[ 0.57388853 -0.65384082 -0.12503025 -1.35744369]
 [-0.98793086  2.15852878  1.04503862 -0.84084403]
 [-1.94635127  0.29190667  0.11179322  0.69624572]
 [ 0.35849259  0.41274034  1.04062847  1.17213343]]
[[ 2 -2 -2 -2]
 [-2  2  2 -2]
 [-2  2  2  2]
 [ 2  2  2  2]]


In [138]:
names= np.array(['Seoul','Daejun','Chungju','seoul','chungju','Daejun','Daejun'])
data = np.random.randn(7,4)
print(data)
print()
print(names =='Seoul') # 1,0,0,0,0,0,0
print()
print(data[names=='Seoul'])

[[-1.33387353 -0.05697712 -0.47477367  1.67878066]
 [-1.55811669  1.25179233 -0.44413448  1.90537388]
 [ 0.65202742 -1.48001886 -2.14199671 -1.94613552]
 [ 1.40291708  0.90303814 -0.82805813  0.46126068]
 [ 1.3312781  -2.40184939 -0.3911907   0.75079595]
 [-0.46314672 -1.09160488  0.24097547  0.30323691]
 [-1.1041949   1.47161209 -1.15087493  0.92174993]]

[ True False False False False False False]

[[-1.33387353 -0.05697712 -0.47477367  1.67878066]]


In [167]:
# 문제
# 다음 데이터를 이용하여 두개다 참일때는 0, cond1이 참일때는 1, cond2가 참일때는 2 그외 때는 3으로 처리 하여 출력
result = []
cond1 = np.array([1,0,1,1,0,0,1], dtype =bool)
cond2 = np.array([0,1,1,1,0,1,1], dtype =bool)


In [160]:
result = np.where(cond1 & cond2,0,np.where(cond1==True,1,np.where(cond2==True,2,3)))
print(result)

[1 2 0 0 3 2 0]


In [162]:
for cond1,cond2 in zip(cond1,cond2):
    if cond1 ==True and cond2 == True:
        result.append(0)
    elif cond1 ==True:
        result.append(1)
    elif cond2==True:
        result.append(2)
    else:
        result.append(3)
    
print(result)

[1, 2, 0, 0, 3, 2, 0]


In [170]:
for i in range(len(cond1)):
    if cond1[i] and cond2[i]:
        result.append(0)
    elif cond1[i]:
        result.append(1)
    elif cond2[i]:
        result.append(2)
    else:
        result.append(3)
    
print(result)

[1, 2, 0, 0, 3, 2, 0]


In [166]:
result = 1*(cond1 & ~cond2) + 2*(cond2 & ~cond1) + 3* ~(cond1|cond2)
print(result)

[1 2 0 0 3 2 0]


In [173]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

z = np.zeros_like(x) # 다른 랭렬과 같은 사이즈로 초기화 
for i in range(10000):
    z[i] = x[i] + y[i]
print(z)

[10002 10004 10006 ... 29996 29998 30000]


In [175]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
print(np.all(a==b)) # 요소 전체가 참일때 참
print(np.any(a==b)) # 요소 하나라도 참이면 참
print(np.exp(a)) # 지수함수(자연대수 : 2.718)

False
True
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [176]:
# 선형대수 : 선형으로 해결하자 => 비선형도 잘게 나누면 선형
# 내적 : 두 백터사이각
# A = (1,2,3), B = (2,3,4)
# A·B = 20(1*2+2*3+3*4)
#cosθ = A·B / |A||B|
#θ = acos(A·B / |A||B|)
